- .eleventy.js
- _data/assetPaths.json
- package-lock.json
- package.json
- Adds config setting for csv `_data` file support
- Bumps npm dependencies
> Bumps devs and adds data file support for csv

- _includes/tagline.html
- Removes a period in the header
-
-
[Note the any security considerations here, or make note of why there are none]
> remove that persky period

- posts/2022-11-21-2023-smartpay-forum.md
> Adds alert banner

- .eleventy.js
- package-lock.json
- package.json
- posts/2022-11-21-2023-smartpay-forum.md
- Adds and configures `markdown-it-attrs` package to support adding css in markdown files
CSS class syntax:
```
```
> Adds ability to apply css to markdown

- _data/site.yaml
- _includes/components/childsidenav.njk
- _includes/components/hero.njk
- _includes/components/sidebar.njk
- _includes/layouts/smarttax.njk
- pages/smarttax/about-smarttax.md
- pages/smarttax/common-questions-about-state-taxes.md
- pages/smarttax/index.md
- pages/smarttax/legal-history.md
- pages/smarttax/recognizing-your-account.md
- pages/smarttax/specific-state-tax-information.md
- pages/smarttax/surcharges.md
set up base navigation for smarttax using USWDS side nav, updated content for legal history
> resolve issue#11 legal history

- pages/smarttax/legal-history.md
per PO feedback of QA review for issue 11, updated the content link accordingly
> resolve PO feedbacks for issue 11

- _includes/layouts/smarttax.njk
- pages/smarttax/about-smarttax.md
- pages/smarttax/common-questions-about-state-taxes.md
- pages/smarttax/index.md
- pages/smarttax/legal-history.md
- pages/smarttax/recognizing-your-account.md
- pages/smarttax/specific-state-tax-information.md
made modification accordingly based on finalized contents updates. PO approved to merge into main branch.
> fixed issue #11

- _data/accounts.yaml
- pages/smarttax/recognizing-your-account.njk
This pull request edits the content to the style guide as described [in this comment](https://github.com/GSA/smartpay-website/issues/15#issuecomment-1434815941).
> Recognizing your account | style guide edits

- .pa11yci-desktop
- .pa11yci-mobile
- _includes/layouts/smarttax.njk
- _includes/layouts/state-tax.njk
- federalist.json
Implements #14
https://github.com/GSA/smartpay-website/issues/14#issuecomment-1448959809
> Add dropdowns to each state page

- src/content/faq/cardholder.mdx
- src/content/faq/government-shutdown.mdx
- src/content/faq/merchants.mdx
- src/content/faq/program-coordinator.mdx
- src/content/faq/state-tax.mdx
Merge destination is _not_ `main`. This will merge into open `wwang-issue16-astro` branch.
- Changes link paths to anticipated internal paths
- Changes "tax map" references to "tax information"
> FAQ – Fixes links, changes tax map wording

- src/content/about/business-lines.md
- src/content/about/index.md
- src/content/about/refunds.md
- About pages were merged prior to #154
- Fixes internal links based on #154.
- [About page](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-about-patch-links/about/)
- [Refunds page](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-about-patch-links/about/refunds/)
> Patches About section internal links

- src/components/GSAHeader.astro
- src/components/PrimaryMenuItem.astro
- src/content/stakeholders/account-holders.md
- src/content/stakeholders/program-coordinators.md
- src/pages/stakeholders/[...slug].astro
This adds the astro page to pull in stakeholder content.  It is still in draft because the content is inconsistent with the top menu (and there is a wrapping issue with the text).
> add astro page for stakeholders

- src/components/SideNav.astro
- src/content/smartbulletins/smart-bulletins.yaml
- src/pages/policies-and-audits/[...slug].astro
- src/pages/policies-and-audits/smart-bulletins/index.astro
Here's the idea for the small change in the side nav for bulletins.
> change side nave to use yaml data too

- src/content/policies-and-audits/audits.md
- Fixes paths for select audit pages
> Fix audit page path typos

- src/content/smarttax/recognizing-your-account.mdx
- makes heading levels progress for H2 to H3 for proper ordering. 
- remove random semicolon.
> make heading levels consistent

- src/content/smarttax/recognizing-your-account.mdx
This bumps a heading level up one for the Sixth Digit Billing Type per request from design.
> one more heading level change per design

- src/content/stakeholders/index.md
-  replace account holders with card/account holders on stakeholder page.
> small content change 

- src/content/state-taxes/montana.md
- src/content/state-taxes/new-hampshire.md
- src/content/state-taxes/north-dakota.md
- src/content/state-taxes/oregon.md
- src/content/state-taxes/south-dakota.md
- a handful of edits to state pages 
- ~waiting on a couple questions before PR~
> Several content edits on state taxes

- src/content/faq/faq.mdx
- src/content/publications/all-business-lines.mdx
- Added emergency use section of FAQ
- update Link to the emergency use FAQs in business line page
> resolve issue 242, added new emergency use section of FAQ

- src/components/BusinessCard.astro
- src/components/Businesslines.astro
- src/components/PrimaryMenuItem.astro
- Address purchase card render issue
- Fixed AMP complaint, fixed the only first white space is been replaced issue
- Address the new card images messed up all business line layout issue
> fixed purchase card render differently issue

- src/content/state-taxes/maryland.md
Updated text for required documentation for CBAs.
> Ayl md tax updates

- src/components/GSAHeader.astro
This adds the <form> snippet from search.gov allowing site searches through search.gov
> Add search.gov's form to allow for site-wide search

- README.md
This customizes the readme to add specific information that may be helpful to developers.
> Customize the default astro readme file

- src/content/faq/faq.mdx
Updating the answer to "Do I still have to pay my individually billed travel card bill?" for the government shutdown FAQ.
> Update government shutdown faq.mdx

- src/content/contact/customer-support.mdx
Sorry! There was a spacing issue that I had to correct. Let's try this again. :)
> Rebekahperillo patch 092623v2

- src/content/how-it-works/index.mdx
Update How GSA SmartPay® Works page per USWDS guidance, as well as some content clean up to reflect card/account and goods/services language.
> Rebekah102023

- src/content/about/business-lines.mdx
- src/content/contact/banks-contact.mdx
- src/content/contact/customer-support.mdx
- src/content/faq/faq.mdx
Updated intros for "Contact", updated some staffing changes in "Contact", updated some Integrated card/account information, and uploaded the Strategic Sources publication that does not contain the office's outdated phone number.
> Rebekah112923v2

- src/content/resources/tools/FASCSA-order-check.md
Changed http://sam.gov to https://sam.gov
> Addressed code review comments.

- src/content/nav/menu.yaml
- src/content/resources/events.md
- src/content/resources/publications.md
- src/content/resources/tools/american-security-drone-act.mdx
Added new page to the resource section with Information about the American Security Drone Act Of 2023.
> Feature/issue 396/american drone act text

- src/content/state-taxes/colorado.md
Updated tax information for Colorado
> Beall011024

- src/content/resources/events.md
https://github.com/GSA/smartpay-website/issues/444
> remove for presentation section.

- src/content/policies-and-audits/audits.md
https://github.com/GSA/smartpay-website/issues/447
> Add new link to dod pdf on audit page.

- src/content/smart-bulletins/022.md
- src/content/smartbulletins-old/smart-bulletins.yaml
https://github.com/GSA/smartpay-website/issues/463
> Updates to SB 022.

- src/components/USAIdentifier.astro
https://github.com/GSA/smartpay-website/issues/474
> Update Accessability link in footer

- src/content/smart-bulletins/033.md
This will create a description meta tag on the page that will be picked up when keywords are searched using a search engine.
> Add description property to smart bulletin No. 033 for page meta tag.

- src/components/FAQSideNav.astro
- src/content/faq/faq.mdx
- src/pages/smarttax/tax-information-by-state/[slug].astro
Updated links in FAQ to point to the new state tax information path 
Updated the parent navigation link to the new path when on mobile
> Production Code Review (per Mark's review)

- src/content/about/index.md
https://github.com/GSA/smartpay-website/issues/496
> Update agency count.

- src/content/about/benefits.md
- src/content/about/business-lines.mdx
- src/content/smarttax/recognizing-your-account.mdx
https://github.com/GSA/smartpay-website/issues/492
> Update broken CCP links.

- src/content/smart-bulletins/022.md
https://github.com/GSA/smartpay-website/issues/511
> Update smart bulletin #22.

- src/content/smart-bulletins/022.md
https://github.com/GSA/smartpay-website/issues/511
> Update 022.md fix casing

- src/content/smart-bulletins/022.md
- src/content/smart-bulletins/023.md
- src/content/smart-bulletins/024.md
- src/content/smart-bulletins/030.md
- src/content/smart-bulletins/031.md
https://github.com/GSA/smartpay-website/issues/511
> Add missing trademarks to SB titles.

- src/content/smart-bulletins/014.md
https://github.com/GSA/smartpay-website/issues/524
> Update sb 14s title

- src/content/smart-bulletins/014.md
Issue #524 Smart Bulletin No. 14 has the wrong title
> Smart Bulletin 014 Intro Update for Production Release

- src/content/about/benefits.md
Issue #527 Remove the cost benefit savings information
> Remove benefit information.

- package-lock.json
- src/content/faq/faq.mdx
Release includes the following issues:
Issue #386 Add Prohibited Vendors to the FAQs
Issue #502 Dependabot Alert
Issue #487 Dependabot Alert
Issue #503 Dependabot Alert
Issue #462 Dependabot Alert
Issue #501 Dependabot Alert
> Production Release

- src/content/about/statistics.md
- src/content/contact/customer-support.mdx
- src/content/resources/events.md
- src/content/smart-bulletins/032.md
- src/content/smart-bulletins/037.md
- src/content/smart-bulletins/038.md
- src/content/smarttax/recognizing-your-account.mdx
Content updates for text corrections, typos, and style updates for May 2024.
> 532 Program Website Content Changes - May

- src/content/nav/menu.yaml
- src/content/resources/visa-supplier-search.md
Visa Supplier Search
[#533](https://github.com/GSA/smartpay-website/issues/533)
> Update Supplier Research to visa supplier search.

- src/config/redirects.js
- src/content/about/statistics.md
- src/content/contact/customer-support.mdx
- src/content/nav/menu.yaml
- src/content/resources/events.md
- src/content/resources/forum-presentations.md
- src/content/resources/publications.md
- src/content/resources/visa-supplier-search.md
- src/content/smart-bulletins/032.md
- src/content/smart-bulletins/037.md
- src/content/smart-bulletins/038.md
- src/content/smarttax/recognizing-your-account.mdx
This release includes the following issues:
- Replace SB No. 022 on Events Page [#521](https://github.com/GSA/smartpay-website/issues/521)
- Redirect 404 link old prohibited vendors [#522](https://github.com/GSA/smartpay-website/issues/522)
- Program Website Content Changes - May [#532](https://github.com/GSA/smartpay-website/issues/532)
- FPDS Link Removal [#535](https://github.com/GSA/smartpay-website/issues/535)
- Visa Supplier Search [#533](https://github.com/GSA/smartpay-website/issues/533)
> merge in staging.

- src/content/contact/customer-support.mdx
Remove Perry Hampton from Contacts
> Update customer-support/remove Perry Hampton.mdx

- .github/workflows/test.yml
- linkinator-config.json
- package-lock.json
- package.json
- src/content/audits/2014-va-purchase.mdx
- src/content/publications/purchase.mdx
- src/content/publications/videos.mdx
Dependabot Alert: tough-cookie Prototype Pollution vulnerability
[#403](https://github.com/GSA/smartpay-website/issues/403)
> migrate link checker over to linkinator.

- src/plugins/process_anchors.js
Code Scanning Alert: Incomplete URL substring sanitization
[#551](https://github.com/GSA/smartpay-website/issues/551)
> fix url substring sanitization.

- src/content/about/master-contract.md
Remove the duplicate content on master contract.  Removed the 2nd bulletin under GSA SmartPay 3 Master Contract
> #558 Remove duplicate content on master-contract.md

- src/content/policies-and-audits/smart-bulletins.md
Add Smart Bulletin to the side navigation under Policies & Audits
[#531](https://github.com/GSA/smartpay-website/issues/531)
> Add smart bulletins to parents side nav.

- src/content/resources/american-security-drone-act.mdx
Changes the LI structure to correct an issue flagged by AMP on 06/21/2024 on the https://smartpay.gsa.gov/resources/american-security-drone-act/ page.
>    Update american-security-drone-act.mdx

- src/content/smart-bulletins/001.md
Remove extra chars from SB 001 #582
> remove extra chars from SB 001.

- src/content/smart-bulletins/037.md
Typo Fixes in Smart Bulletin 037
[#583](https://github.com/GSA/smartpay-website/issues/583)
> Update incorrect quote marks on sb37.

- src/content/state-taxes/ohio.md
> Update Ohio tax information.

- src/content/audits/2020-gao-disaster-response.mdx
Replace GAO Audit PDF
[#643](https://github.com/GSA/smartpay-website/issues/643)
> Remove gao audit pdf.

- src/content/contact/customer-support.mdx
Update Contact Information for New Contract Team Members
[#639](https://github.com/GSA/smartpay-website/issues/639)
> Add new contacts.

- src/content/resources/forum-presentations.md
Remove the GSA020 presentation
[#657](https://github.com/GSA/smartpay-website/issues/657)
> Remove presentation.

- src/content/contact/customer-support.mdx
Update Contact Information
[#656](https://github.com/GSA/smartpay-website/issues/656)
Added two contacts and alphabetized lists
> update contact page.

- src/content/about/master-contract.md
Citi Bank Address
[#662](https://github.com/GSA/smartpay-website/issues/662)
> Address update.

- src/content/about/master-contract.md
Citi Bank Address
[#662](https://github.com/GSA/smartpay-website/issues/662)
> Update citibank address.

- src/content/about/business-lines.mdx
- src/content/helpful-hints/purchase-account.mdx
- src/pages/about/business-lines/helpful-hints/[...slug].astro
Convert PDF: About > Business Lines > Integrated > Helpful Hints for Purchase Account Use -- https://smartpay.gsa.gov/files/purchase-account-helpful-hints.pdf
[#605](https://github.com/GSA/smartpay-website/issues/605)
> Convert helpful hints pdf into html page.

- src/content/resources/events.md
Update Forum 2025
[#655](https://github.com/GSA/smartpay-website/issues/655)
> Update Training Forum Event for 2025.

- src/content/about/business-lines.mdx
- src/content/helpful-hints/fleet-account.mdx
- src/content/helpful-hints/travel-account.mdx
Convert PDF: About > Business Lines > Integrated > Helpful Hints for Travel Account Use -- https://smartpay.gsa.gov/files/travel-account-helpful-hints.pdf
[#606](https://github.com/GSA/smartpay-website/issues/606)
Convert PDF: About > Business Lines > Integrated > Helpful Hints for Fleet Account Use -- https://smartpay.gsa.gov/files/fleet-account-helpful-hints.pdf
[#607](https://github.com/GSA/smartpay-website/issues/607)
Note: the linkchecker will fail. See https://github.com/GSA/smartpay-website/pull/679 for resolution
> Convert Travel and Fleet helpful hints to html.

- src/content/state-taxes/california.md
California Tax
[#688](https://github.com/GSA/smartpay-website/issues/688)
> Update CA gov bank card link.

- src/content/merchants/vendor-guide.mdx
Add missing trademark and update old links to not depend on the redirect.
> Vendor guide updates.

- src/content/faq/faq.mdx
> Update tres FAQ links.

- src/content/smart-bulletins/003.md
- src/content/smart-bulletins/009.md
- src/content/smart-bulletins/015.md
- src/content/smart-bulletins/016.md
- src/content/smart-bulletins/018.md
- src/content/smart-bulletins/021.md
Archived Smart Bulletins - Add new message and address invalid links
[#638](https://github.com/GSA/smartpay-website/issues/638)
> Update archive warnning text.

- src/content/resources/tools/section-889.md
additional content updates for ticket 714
> Additional Content Updates for Ticket 714

- src/plugins/process_anchors.js
Updated the process_anchors.js file to remove vulnerability when determining if a link is internal or external.
> Static Code Vulnerability

- src/content/about/statistics.md
Updated the stat file name, removed the old stat file, added new stat file
> Content/784 update sales, transactions, and card/account holder data

- src/content/about/master-contract.md
- src/content/resources/events.md
Includes the following issues:
2025 Forum Canceled - Please update #825
Update master contract on website #828
> Emergency Release

- src/components/Callout.astro
- src/content/about/master-contract.md
Remove SmartPay 4 ideas/email/image and replace #836
> Remove SmartPay 4 ideas/email/image and replace

- src/content/smart-bulletins/020.md
> Applying production code review comments to staging. 

- src/content/smart-bulletins/041.md
> Add new smart bulletin

- package-lock.json
- package.json
Update devDependency start-server-and-test library to fix vulnerability in transitive dependency
> axios Requests Vulnerability

- package-lock.json
- package.json
Addressed the following dependabot issue:
tar-fs Vulnerable to Link Following and Path Traversal via Extracting a Crafted tar File
> Dependabot Vulnerability

- package-lock.json
- package.json
Updated to latest Astro version to address vulnerability in transitive dependency
> Dependabot Vulnerability 

- src/components/BackToTop.astro
Adding z index to back to top container to prevent being covered up by other components on page when screen is minimized.
> Merging production code review comments back into staging
